version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-graalvm
    ports:
      - 8081:8081
    environment:
      - TODOSERVICE_URL=http://todo-service:8080
  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile-graalvm
    ports:
      - 8080:8080
